In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
final = pd.read_csv('C:\\Users\\scher\\school\\senior-thesis\\data\\rso_data.txt', index_col=0)
final = final[final['Year']==2019].reset_index().drop(columns='index')
final

,Year,Organization,Type,Designation,Standing,Allocation
0,2019,The B-Side,PUB,Publications RSO,7,350.0
1,2019,BARE Magazine,PUB,Publications RSO,12,4077.0
2,2019,Berkeley Economic Review,PUB,Academic RSO,2,700.0
3,2019,Berkeley Fiction Review,PUB,Publications RSO,36,2000.0
4,2019,Berkeley Poetry Review,PUB,Publications RSO,25,1520.0
...,...,...,...,...,...,...
521,2019,Volunteers for Medical Outreach,SISG,Service RSO,6,2200.0
522,2019,Wonderworks,SISG,Service RSO,9,0.0
523,2019,You Mean More,SISG,Health & Wellness RSO,8,1500.0
524,2019,Youth Empowerment Program,SISG,Service RSO,6,1850.0
525,2019,Youth Support Program,SISG,Service RSO,24,800.0

In [11]:
initial = pd.read_csv('C:\\Users\\scher\\school\\senior-thesis\\data\\reformatted\\2019-2020_initial.txt', 
                      delimiter='\t',
                      usecols=[1,3,5,7],
                      names=['Organization', 'Type', 'Standing', 'Allocation'])
initial = initial[initial['Type'].isin(['PUB','SAG','SISG'])]
initial['Standing'] = initial['Standing'].apply(int)

def clean_alloc(alloc):
    if alloc == 'Sponsorship Only' or alloc == 'Sponsorship only' or alloc == 'Sponsorsphip Only':
        return 0
    
    alloc = alloc.replace('$','')
    
    if ',' in alloc:
        alloc = alloc.replace(',','')
        
    return float(alloc)

initial['Allocation'] = initial['Allocation'].apply(clean_alloc)

initial

                                Organization  Type  Standing  Allocation
18                               B-Side, The   PUB         7       350.0
19                             BARE Magazine   PUB        12      4077.0
20                  Berkeley Economic Review   PUB         2       700.0
21                   Berkeley Fiction Review   PUB        36      2000.0
22                    Berkeley Poetry Review   PUB        25      1520.0
..                                       ...   ...       ...         ...
490  Volunteers Around the World at Berkeley  SISG         6       200.0
491          Volunteers for Medical Outreach  SISG         6      2200.0
492                            You Mean More  SISG         8      1500.0
493                Youth Empowerment Program  SISG         6      1850.0
494                    Youth Support Program  SISG        24       800.0

[477 rows x 4 columns]